
/**
 * CREATE TWEET TABLE
 */
CREATE TABLE IF NOT EXISTS tweets (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    tweet_id BIGINT NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

/**
 * CREATE NEWS TABLE
 */
CREATE TABLE IF NOT EXISTS news (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source VARCHAR(191),
    news_id BIGINT,
    timestamp BIGINT NOT NULL,
    storage_date VARCHAR(191) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;